config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
RedmineApp::Application.routes.draw do
	scope '/projects/:project_id/', :as => "project" do
		
		match 'gestion_garantias', to: 'gg_files#index', as: 'gg_home'

		resources :csme_files, :controller => 'gg_files', :as => 'gg_files' do
			resources :articles, :controller => 'gg_articles', :as => 'gg_articles' do
				get :copy, on: :member
				resources :contacts, :controller => 'gg_contacts', :as => 'gg_contacts'
				resources :ans, :controller => 'gg_ans', :as => 'gg_ans'
			end
		end
	end

	# Ruta para comprobar si existe un usuario con un determinado e-mail a través de AJAX
	get '/find_user', to: 'gg_articles#find_user', as: 'find_user'

	# Ruta para crear un usuario mediante el modal a través de AJAX
	get '/modal_create_user', to: 'gg_articles#modal_create_user', as: 'modal_create_user'
end

app/models/gg_article.rb
class GgArticle < ActiveRecord::Base
  unloadable
  
  belongs_to :gg_file, :primary_key => :identity_file, :foreign_key => :gg_file_id
  has_one :contacts, :dependent => :destroy, :class_name => "GgContact", :foreign_key => "article_id", :primary_key => "article_id", :autosave => true
  has_many :gg_ans, :class_name => 'GgAns', :dependent => :destroy, :foreign_key => "gg_article_id", :primary_key => "article_id"
  accepts_nested_attributes_for :gg_ans, :contacts

  validates :code_article, :numericality => { :message => l(:"article.error.validation_code_article_number")}
  validate :code_article_is_blank
  validate :code_provider_is_blank
  validate :name_provider_is_blank
  validates :article_id, presence: true

  # Si no existen los contactos del artículo, los inicializa
  def contacts_with_initialize
    contacts_without_initialize || build_contacts
  end
  alias_method_chain :contacts, :initialize

  def users
    if contacts.present?
      [contacts.first_level, contacts.second_level, contacts.third_level]
    else
      [nil, nil, nil]
    end
  end

  # Genera mensaje de error
  def get_error_message
    error_msg = ""
    self.errors.full_messages.each do |msg|
      if error_msg != ""
        error_msg << "<br>"
      end
      error_msg << msg
    end

    error_msg
  end

  # Muestra los contactos del articulo en el dialog.
  def show_contacts
    if self.users[0].nil? && self.users[1].nil? && self.users[2].nil?
      "<i>"+l(:"contact.empty")+"</i><br><hr>"
    else
      self.users.reject{|c| c.nil?}.collect{|c| "<div style='float: left; width: 200px'><b>"+c.firstname+" "+c.lastname+"</b></div> <div style='float: left; width: 250px; margin-left: 10px;'> <i>"+c.mail+"</i></div> | "+(c.phone.present? ? c.phone : "Sin número de contacto.")+" | <hr>"}.join('')
    end
  end

  private
  # Valida que el código de articulo no se encuentre vacío.
  def code_article_is_blank
 	  errors.add :base, l(:"article.error.validation_code_article_blank") if self.code_article.blank?
  end
  
  # Valida que el código del proveedor no se encuentre vacío.
  def code_provider_is_blank
    errors.add :base, l(:"article.error.validation_code_provider_blank") if self.code_provider.blank?
  end

  # Valida que el nombre del proveedor no se encuentre vacío.
  def name_provider_is_blank
 	  errors.add :base, l(:"article.error.validation_name_provider_blank") if self.name_provider.blank?
  end

end

app/controllers/gg_articles_controller.rb
class GgArticlesController < ApplicationController
  unloadable

  menu_item :config_gestion_garantias 
  before_filter :find_project_by_project_id, :authorize, :except => [:find_user, :modal_create_user]

  before_filter :set_article, only: [:edit, :update, :destroy]
  before_filter :set_file, only: [:new, :create, :edit, :update, :copy, :destroy]

  def new
    # @article = GgArticle.new

    # @ans = []
    # (0...1).each do |i|
    #   @ans[i] = GgAns.new(:id => i) 
    # end

    # @count_ans = 1
  end

  def create
    @article = GgArticle.new params[:gg_article]

    if @article.save
      flash[:notice] = l(:"article.notice_create")
      redirect_to  edit_project_gg_file_path(@file, :project_id => @project)
    else
      flash[:error] = @article.get_error_message
      redirect_to action: 'new', :project_id => @project
    end
  end

  def edit
    @contacts = @article.users

    @ans = @article.gg_ans
    @count_ans = @article.gg_ans.count
  end

  def update 
    if @article.update_attributes(params[:gg_article]) 
      flash[:notice] = l(:"article.notice_edit")
      redirect_to edit_project_gg_file_path(@file, :project_id => @project)
    else
      flash[:error] = @article.get_error_message
      redirect_to action: 'edit', :project_id => @project
    end
  end

  def copy
    # old_article = GgArticle.find(params[:id])
    # @article = old_article.dup
    # @article.code_article = ""

    # @ans = old_article.gg_ans.map(&:dup)
    # @count_ans = @ans.count
  end

  def destroy
    if @article.destroy
      flash[:notice] = l(:"article.notice_destroy")
    else
      flash[:error] = l(:"article.error.action_destroy")
    end

    redirect_to edit_project_gg_file_path(@file, :project_id => @project)
  end

  def find_user
    user = User.where("mail = ?", params[:user_email]).select([:id, :firstname, :lastname, :mail]).first

    respond_to do |format|
      user[:phone] = user.phone if user.present? 
      format.json { render json: {:user => user.present? ? user.attributes : nil, :user_present => user.present? ? true : false} }
    end
  end

  def modal_create_user
    # Creación del usuario.
    @user           = User.new
    @user.login     = params[:login]
    @user.firstname = params[:firstname]
    @user.lastname  = params[:lastname]
    @user.mail      = params[:mail]

    # Generar contraseña random combinando letras (mayusculas y minusculas).
    chars = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    @user.password  = (0...8).map { chars[rand(chars.length)] }.join

    if @user.save
      # Añadimos el usuario creado al grupo de 'Servicio Técnico'.
      group = Group.find Setting.plugin_gestion_garantias[:gg_group_provider_contacts]
      group.users << @user

      # Añadimos el número de telefono del usuario.
      @user.custom_value_for(Setting.plugin_gestion_garantias[:gg_field_user_phone]).value = params[:phone]
      @user.custom_value_for(Setting.plugin_gestion_garantias[:gg_field_user_phone]).save
      
      # Envio al usuario de que la cuenta ha sido creada. 
      Mailer.account_information(@user, @user.password).deliver

      respond_to do |format|
        format.json { render json: { msg: "Usuario creado con éxito.", type: "notice"} }
      end
    else
      respond_to do |format|
        format.json { render json: { msg: @user.get_error_message, type: "error"} }
      end
    end
  end

  private
  def set_article
    @article = GgArticle.find params[:id]
  end

  def set_file
    @file = GgFile.find params[:gg_file_id]
  end

end

app/views/gg_articles/partials/_form.html.erb
<div class="flash" style="display: none;"></div>

<div id="prueba">
<%= csrf_meta_tag %>
<% content_for :header_tags do %>
	<%= javascript_include_tag "gg_articles.js", :plugin => 'gestion_garantias' %>
   <%= stylesheet_link_tag "/gg_articles.css", :plugin => 'gestion_garantias', :media => "screen" %>
<% end %>

<%= form_for [@project, @file, @article] do |f| %>
<div class="splitcontentleft articles_form_left">
	<h2><%= l(:"file.file") %></h2>
		<table class="list">
	<thead>
	<tr>
	   <th><%= l(:"file.code_file") %></th>
	</tr>
	</thead>
		<tbody>
			 <tr class="<%= cycle("odd", "even") %>">
			 	<td><%= @file.code_file %></td>
			 </tr>
		</tbody>
	</table><br>

	<fieldset>
		<legend><h2><%= l(:"article.article") %></h2></legend>
		<%= f.hidden_field :gg_file_id, :value => @file.identity_file %>

		<div><%= f.label l(:"article.code_article")+": " %></div>
		<%= f.text_field(:code_article, :size => 33) %>

		<div><%= f.label l(:"article.code_type_material")+": " %></div>
		<%= f.text_field(:code_type_material, :size => 33) %>

		<div><%= f.label l(:"article.code_provider")+": " %></div>
		<%= f.text_field(:code_provider, :size => 33) %>

		<div><%= f.label l(:"article.name_provider")+": " %></div>
		<%= f.text_field(:name_provider, :size => 33) %>
	</fieldset>
</div>	

<div class="splitcontentright articles_form_right">
	<fieldset class="f_contacts">
		<legend><h2><%= l(:"contact.contacts") %></h2></legend>
		<%= f.fields_for :contacts, @article.contacts do |f2| %>
			<%= f2.hidden_field :level_1 %>
			<%= f2.hidden_field :level_2 %>
			<%= f2.hidden_field :level_3 %>

			<%= render :partial => "gg_articles/partials/form_contact", :locals => {:user => @article.contacts.first_level, :level => 1 } %>
			<%= render :partial => "gg_articles/partials/form_contact", :locals => {:user => @article.contacts.second_level, :level => 2 } %>
			<%= render :partial => "gg_articles/partials/form_contact", :locals => {:user => @article.contacts.third_level, :level => 3 } %>
		<% end %>
	</fieldset>
</div>
	<div style="clear: both"></div>
	
	<fieldset>
		<legend><h2><%= f.label l(:"ans.ans_description") %></h2></legend>
		<% (0...@count_ans).each do |i| %>
			<%= f.fields_for :gg_ans, @ans[i] do |j| %>

				<fieldset class="f_ans field_for_ans_<%= i %>">
				<p class="l_ans"><%= j.label l(:"ans.priority")+": " %></p>
				<%= j.text_field(:priority, :class => "t_ans") %>
				<p class="l_ans"><%= j.label l(:"ans.description")+": " %></p>
				<%= j.text_area(:description, :class => "t_ans", :rows => 7) %>
				<%= link_to '<span class="icon icon-del detele_text">'.html_safe+l(:text_delete), project_gg_file_gg_article_gg_an_path(@file,@article,@ans[i], :project_id => @project), :confirm => l(:"ans.confirm_delete"), :method => :delete, class: "delete_ans_rails" if !@ans[i].new_record? %>
				</fieldset>

			<% end %>
		<% end %>

		<div class="contextual btn_add_ans">
		    <a><span class="icon icon-add add_ans" data-count="<%= @count_ans %>"><%= l(:"ans.new") %></span></a>
		</div>
	</fieldset>

	<div>
	<%= f.submit l(:"text_save"), style: "float: left;", class: "form_articles_button" %>
	</div>
<% end %>
<%= button_to l(:"text_back"), edit_project_gg_file_path(@file, :project_id => @project), class: "form_articles_button form_articles_button_back", :method => :get %>
</div>

<%= render :partial => "gg_articles/partials/form_contact_create" %>

<script>
	// Configuración de la ventana modal para crear nuevos usuarios.
	$(".dialog_create_user").dialog({
		autoOpen: false,
		modal: true,
		minWidth: 500,
		close: function(event, ui){
			$('.in_use').removeClass('in_use');
		}
	});
</script>

app/views/gg_articles/partials/_form_contact.html.erb
<fieldset class="f_level">
	<legend><u><%= l(:"contact.level") %> <%= level %></u></legend>
			<div class="div_contact contact_email_<%= level %>">
				<p class="l_contact"><%= label_tag l(:"contact.email")+": " %></p>
				<%= text_field_tag :email, user.present? ? user.mail : nil, { data: {level: level}, :size => 30, class: "input_contact_email input_contact_email_"+level.to_s } %>
			</div>
			<div class="contact_exist_<%= level %>" style="<%= 'display:none;' if !user.present? %>" >
				<div class="div_contact contact_name_<%= level %>">
					<p class="l_contact"><%= label_tag l(:"contact.name")+": " %></p>
					<%= user.firstname + " " + user.lastname if user.present? %>
				</div>

				<div class="div_contact_phone contact_phone_<%= level %>">
					<p class="l_contact"><%= label_tag l(:"contact.phone")+": " %></p>
					<%= user.phone if user.present? %>
				</div>
			</div>
			<div class="contact_not_exist_<%= level %>" style="display:none;">
				<div class="div_contact_button div_contact_button_<%= level %>">
				<%= button_tag "Crear usuario", { data: {level: level}, class: "btn_create_contact" } %>
				</div>
				<p class='notice_create_user'><i><%= l(:"contact.email_not_found") %></i></p>
			</div>
</fieldset>

app/views/gg_articles/partials/_form_contact_create.html.erb
<div class="dialog_create_user" title="Registro de un nuevo usuario">
	<%= form_tag :user, {:id => "formModalUser"} do %>
		<div class="div_dialog_create_user">
			<hr>
			<div class="dialog_user_content">
				<div class="dialog_user_label"><b><%= l(:"contact.e-mail") %>* </b></div> 
				<div id="dialog_user_email"></div>
				<%= hidden_field_tag :mail %>
			</div>

			<div class="dialog_user_content">
				<div class="dialog_user_label"><b><%= l(:"contact.user") %>* </b></div>
				<%= text_field_tag :login, nil, size: 20, class: "dialog_user_name" %><br>
			</div>

			<div class="dialog_user_content">
				<div class="dialog_user_label"><b><%= l(:"contact.name") %>* </b></div>
				<%= text_field_tag :firstname, nil, size: 25, class: "dialog_user_firstname" %>
			</div>

			<div class="dialog_user_content">
				<div class="dialog_user_label"><b><%= l(:"contact.surname") %>* </b></div>
				<%= text_field_tag :lastname, nil, size: 25, class: "dialog_user_lastname" %>
			</div>

			<div class="dialog_user_content">
				<div class="dialog_user_label"><b><%= l(:"contact.phone") %> </b></div>
				<%= text_field_tag :phone, nil, size: 20, class: "dialog_user_lastname" %>
			</div>
			<hr>

			<p><button type="submit" id="dialog_user_btn_create"><%= l(:"contact.create")%></button><div class="dialog_user_msg_error" style="display:none;"><%= l(:"contact.error.email_not_valid") %></div></p>
		</div>
	<% end %>
</div>