config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
RedmineApp::Application.routes.draw do
	scope '/projects/:project_id/', :as => "project" do
		
		match 'gestion_garantias', to: 'gg_files#index', as: 'gg_home'

		resources :csme_files, :controller => 'gg_files', :as => 'gg_files' do
			resources :articles, :controller => 'gg_articles', :as => 'gg_articles' do
				get :copy, on: :member
				resources :contacts, :controller => 'gg_contacts', :as => 'gg_contacts'
				resources :ans, :controller => 'gg_ans', :as => 'gg_ans'
			end
		end
	end

	# Ruta para comprobar si existe un usuario con un determinado e-mail a través de AJAX
	get '/find_user', to: 'gg_articles#find_user', as: 'find_user'

	# Ruta para crear un usuario mediante el modal a través de AJAX
	get '/modal_create_user', to: 'gg_articles#modal_create_user', as: 'modal_create_user'
end

app/models/gg_file.rb
class GgFile < ActiveRecord::Base
  unloadable

  has_many :gg_articles, :dependent => :destroy, :primary_key => :identity_file, :foreign_key => :gg_file_id

  validate :identity_file_is_blank
  validate :identity_file_is_number
  validate :identity_file_is_unique
  validate :code_file_is_blank

  # Genera mensaje de error
  def get_error_message
    error_msg = ""
    
    self.errors.full_messages.each do |msg|
      if error_msg != ""
        error_msg << "<br>"
      end
      error_msg << msg
    end

    error_msg
  end

  private
  # Valida que el campo del numero de identidad del expediente no se encuentre vacio.
  def identity_file_is_blank
  	 errors.add :base, l(:"file.error.validation_indentity_file_blank") if self.identity_file.blank?
  end

  # Valida que el identificador del expediente es un número
  def identity_file_is_number
    errors.add :base, l(:"file.error.validation_identity_file_number") if (self.identity_file.is_a? Integer) == false
  end

  # Valida que el identificador de expediente sea un número único.
  def identity_file_is_unique
    errors.add :base, l(:"file.error.validation_identity_file_unique") if GgFile.where("identity_file = ?", self.identity_file).present?
  end

  # Valida que el campo del código del expediente no este vacio.
  def code_file_is_blank
     errors.add :base, l(:"file.error.validation_code_file_blank") if self.code_file.blank?
  end

end

app/controllers/gg_files_controller.rb
class GgFilesController < ApplicationController
  unloadable

  menu_item :config_gestion_garantias 
  before_filter :find_project_by_project_id, :authorize
  before_filter :set_file, only: [:edit, :update, :destroy]

  def index
    limit = params[:per_page].present? ? params[:per_page].to_i : 29
    page_num = params[:page].present? ? params[:page].to_i : 0
    offset = params[:page].present? ? ((page_num-1) * limit ) : 0

    # Motor de busqueda
    if params[:search_file].present? && params[:type_search_file].present?
      if GgFile.where("#{params[:type_search_file]} = ?", params[:search_file]).present?
        @files = GgFile.where("#{params[:type_search_file]} = ?", params[:search_file]).order("identity_file ASC").offset(offset).limit(limit)
        @files_count = GgFile.where("#{params[:type_search_file]} = ?", params[:search_file]).order("identity_file ASC").count
      else
        flash[:error] = "No se ha encontrado ningun resultado."
        redirect_to action: 'index'
      end
    # En el caso de que no se haya realizado una busqueda.
    else
    	@files = GgFile.order("identity_file ASC").offset(offset).limit(limit)
      @files_count = GgFile.order("identity_file ASC").count
    end

    @files_pages = Paginator.new @files_count, limit, params[:page]
  end

  def new
  	@file = GgFile.new
  end

  def create
  	@file = GgFile.new params["gg_file"]

  	if @file.save
      flash[:notice] = l(:"file.notice_create")
  	  redirect_to project_gg_home_path(:project_id => @project)
    else
      flash[:error] = @file.get_error_message
      redirect_to action: 'new', :project_id => @project
    end
  end

  def edit
    limit = params[:per_page].present? ? params[:per_page].to_i : 29
    page_num = params[:page].present? ? params[:page].to_i : 0
    offset = params[:page].present? ? ((page_num-1) * limit ) : 0
    @articles = @file.gg_articles.order("code_article ASC").offset(offset).limit(limit)
    @articles_count = @file.gg_articles.order("code_article ASC").count
    @articles_pages = Paginator.new @articles_count, limit, params[:page]
  end

  def update 
    if @file.update_attributes(params[:gg_file]) 
      flash[:notice] = l(:"file.notice_edit")
      redirect_to project_gg_home_path(:project_id => @project)
    else
      flash[:error] = @file.get_error_message
      redirect_to action: 'edit', :project_id => @project
    end
  end

  def destroy
    if @file.destroy
      flash[:notice] = l(:"file.notice_destroy")
    else
      flash[:error] = l(:"file.error.action_destroy")
    end

    redirect_to project_gg_home_path(:project_id => @project)
  end

  private
  def set_file
    @file = GgFile.find params[:id]
  end
end

app/views/gg_files/edit.html.erb
<%= csrf_meta_tag %>
<% content_for :header_tags do %>
  <%= javascript_include_tag "gg_files.js", :plugin => 'gestion_garantias' %>
  <%= stylesheet_link_tag "/gg_files.css", :plugin => 'gestion_garantias', :media => "screen" %>
<% end %>

<%= render "gg_files/partials/form" %>
<!-- OCULTADO el boton de crear nuevos artículos
<div class="contextual">
  <%# link_to '<span class="icon icon-add">'.html_safe+l(:"article.new"), new_project_gg_file_gg_article_path(@file, :project_id => @project ) %>
</div>
-->
<fieldset>
<legend><h2><%= l(:"article.articles") %></h2></legend>
<table class="list">
<thead>
<tr>
   <th><%= l(:"article.code_article") %></th>
   <th><%= l(:"article.name_provider") %></th>
   <th><%= l(:"ans.ans") %></th>
   <th><%= l(:"article.permissions") %></th>

</tr>
</thead>
<tbody>
	<% @articles.each do |article| %>
    <tr class="<%= cycle("odd", "even") %> tooltip_contacts" title="<hr><%= article.show_contacts %>">
    	<td><%= link_to article.code_article+"/"+article.code_type_material.to_s, edit_project_gg_file_gg_article_path(@file, article, :project_id => @project) %></td>
    	<td><%= article.name_provider %></td>
    	<td><a href="#" class="button_ans" data-id="<%= article.id %>">Consultar</a></td>
    	<td>
    		<%= link_to '<span class="icon icon-edit">'.html_safe+l(:text_edit), edit_project_gg_file_gg_article_path(@file, article, :project_id => @project) %>
        <%# link_to '<span class="icon icon-copy">'.html_safe+l(:text_copy), copy_project_gg_file_gg_article_path(@file, article, :project_id => @project) %>
        <%= link_to '<span class="icon icon-del">'.html_safe+l(:text_delete), project_gg_file_gg_article_path(@file,article, :project_id => @project), :confirm => l(:"article.confirm_delete"), :method => :delete %>
      </td>
      <div class="dialog_ans dialog_ans_<%= article.id.to_s %>" title="ANS">
          <% if !article.gg_ans.empty? %>
            <% article.gg_ans.each do |ans| %>
              <hr>
                <p class="dialog_ans_title"><%= l(:"ans.priority") %>:</p>
                <p><%= ans[:priority] %></p>
                <p class="dialog_ans_title"><%= l(:"ans.description") %>:</p>
                <p><%= ans[:description] %></p>
              <hr>
            <% end %>
          <% else %>
            <hr>
              <p><i><center><%= l(:"ans.ans_empty") %></center></i></p>
            <hr>
          <% end %>
      <div>
    </tr>
    <% end %>
</tbody>
</table>
<p class="pagination"><%= pagination_links_full @articles_pages, @articles_count %></p>
</fieldset><br>
</fieldset>

app/views/gg_files/index.html.erb
<!-- OCULTADO el boton de crear nuevos expedientes
<div class="contextual">
    <%# link_to '<span class="icon icon-add">'.html_safe+l(:"file.new"), :controller => :gg_files, :action => :new, :project_id => @project %>
</div> 
-->

<div class="contextual">
     <%= form_tag({:controller => 'gg_files', :action => 'index'}, :method => :get ) do %>
        <%= label_tag(:search_file, "Busqueda: ") %>
        <%= text_field_tag(:search_file) %>
        <%= radio_button_tag(:type_search_file, "identity_file") %><%= label_tag(:type_id_file, "Identificador") %>
        <%= radio_button_tag(:type_search_file, "code_file") %><%= label_tag(:type_cod_file, "Código exp.") %>
        <%= submit_tag("Buscar") %>
     <% end %>
</div> 

<h2><%= l(:"file.files") %></h2>

<table class="list">
<thead>
<tr>
   <th><%= l(:"file.identity_file") %></th>
   <th><%= l(:"file.code_file") %></th>
   <th><%= l(:"file.n_providers") %></th>
   <th><%= l(:"file.n_articles") %></th>
   <th><%= l(:"file.permissions") %></th>
</tr>
</thead>
<tbody>
  <% @files.each do |file| %>
    <tr class="<%= cycle("odd", "even") %>">
     <td><%= file.identity_file %></td>
     <td><%= link_to file.code_file, edit_project_gg_file_path(file, :project_id => @project) %></td>
     <td><%= file.gg_articles.select(:name_provider).uniq.count %></td>
     <td><%= file.gg_articles.count %></td>
     <td>
        <%= link_to '<span class="icon icon-edit">'.html_safe+l(:text_edit), edit_project_gg_file_path(file, :project_id => @project) %>
        <%= link_to '<span class="icon icon-del">'.html_safe+l(:text_delete), project_gg_file_path(file, :project_id => @project), :confirm => l(:"file.confirm_delete"), :method => :delete %>
     </td>
    </tr>
  <% end %>
</tbody>
</table>

<p class="pagination"><%= pagination_links_full @files_pages, @files_count %></p>

app/views/gg_files/new.html.erb
<%= render "gg_files/partials/form" %>